plugins { id "com.android.application" }

android {
    namespace "com.hamza.streetsovereign"
    compileSdk 35

    defaultConfig {
        applicationId "com.hamza.streetsovereign"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            debuggable false
        }
    }
}
